- hosts: localhost
  gather_facts: True
  vars:
    enable_demo: False
    broker_ci: False
  vars_prompt:
    - name: dockerhub_user_name
      prompt: "Enter your dockerhub username"
      private: no
    - name: dockerhub_user_password
      prompt: "Enter your dockerhub password"
      private: yes
    - name: dockerhub_org
      prompt: "Enter the dockerhub organization you'd like to pull images from"
      private: no
  roles:
    - "{{ cluster }}_setup"
    - { role: ansible_service_broker_setup, when: not broker_ci }
    - { role: local_demo_prep, when: enable_demo == True }
  post_tasks:
    - set_fact:
        msg: |
            Hostname:                  {{ hostname }}
            Next steps:
            Visit https://{{ hostname }}:8443 for the web console
            OR
            For CLI access:
            oc login --insecure-skip-tls-verify {{ hostname }}:8443 -u {{ cluster_user }} -p {{ cluster_user_password }}
      when: "'{{ cluster }}' == 'openshift'"
    - set_fact:
        msg: |
            Hostname:                  {{ hostname }}
            Kubernetes Cluster is running at http://{{ hostname }}:6443
      when: "'{{ cluster }}' == 'kubernetes'"
    - debug:
        msg: "{{ msg.split('\n') }}"
